#-----------------------------------------------------------------------|
#
#███╗░░░███╗░█████╗░░█████╗░███╗░░██╗██╗░░░░░██╗██╗░░░██╗███████╗
#████╗░████║██╔══██╗██╔══██╗████╗░██║██║░░░░░██║██║░░░██║██╔════╝
#██╔████╔██║██║░░██║██║░░██║██╔██╗██║██║░░░░░██║╚██╗░██╔╝█████╗░░
#██║╚██╔╝██║██║░░██║██║░░██║██║╚████║██║░░░░░██║░╚████╔╝░██╔══╝░░
#██║░╚═╝░██║╚█████╔╝╚█████╔╝██║░╚███║███████╗██║░░╚██╔╝░░███████╗
#╚═╝░░░░░╚═╝░╚════╝░░╚════╝░╚═╝░░╚══╝╚══════╝╚═╝░░░╚═╝░░░╚══════╝
#               Plugin by: Eliseo190 - MoonLive v1.0.1                  |
#-----------------------------------------------------------------------|

servers:
  Network: "Lobby"

messages:
  no-permission: "&d&lMOON&5&LLIVE &8&l» &cNo tienes permisos para hacer esto."
  no-args: "&d&lMOON&5&LLIVE &8&l» &7poner el enlace de tu directo!"
  invalid-url: "&d&lMOON&5&LLIVE &8&l» &7El enlace que escribiste no es valido."
  click: "&d&lPARA VER!"
  liveplaying:
    - "&7&m---------------------------------"
    - "&b%player_name% &eesta en directo jugando &a&l%server_name%"
    - "&8&l&a&l%live%"
    - "&7&m---------------------------------"
  live:
    - "&7&m---------------------------------"
    - "&b%player_name% &eesta en directo"
    - "&8&l&a&l%live%"
    - "&7&m---------------------------------"